'use strict';
angular.module('app').config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$stateProvider.state('main',{
		url:'/main/:id',
		templateUrl:'view/main.html',
		controller:'mainCtrl'
	}).state('bookcity',{
		url:'/bookcity/:name',
		templateUrl:'view/bookcity.html',
		controller:'bookcityCtr'
	}).state('zj',{
		url:'/zj/:id',
		templateUrl:'view/zj.html',
		controller:'zjCtr'
	}).state('xq',{
		url:'/xq/:id',
		templateUrl:'view/xq.html',
		controller:'xqCtrl'
	}).state('cart',{
		url:'/cart/:id',
		templateUrl:'view/cart.html',
		controller:'cartCtr'
	}).state('purchasing',{
		url:'/purchasing/:idx',
		templateUrl:'view/purchasingpage.html',
		controller:'purchasingpageCtr'
	}).state('login',{
		url:'/login',
		templateUrl:'view/login.html',
		controller:'loginCtr'
	}).state('register',{
		url:'/register',
		templateUrl:'view/register.html',
		controller:'registerCtr'
	}).state('me',{
		url:'/me',
		templateUrl:'view/me.html',
		controller:'meCtr'
	})
	 $urlRouterProvider.otherwise('main/0');
}])